/* Generated By:JJTree&JavaCC: Do not edit this line. Prog3Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Prog3Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LAMBDA = 7;
  /** RegularExpression Id. */
  int SUCC = 8;
  /** RegularExpression Id. */
  int SQR = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int LETTER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"L\"",
    "\"succ\"",
    "\"sqr\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"+\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\".\"",
  };

}
