/* Generated By:JavaCC: Do not edit this line. Prog3TreeConstants.java Version 5.0 */
public interface Prog3TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMUL = 3;
  public int JJTVAR = 4;
  public int JJTNUM = 5;
  public int JJTAPPL = 6;
  public int JJTLAMB = 7;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "add",
    "mul",
    "var",
    "num",
    "appl",
    "lamb",
  };
}
/* JavaCC - OriginalChecksum=c61f626af667cb3af9489935fa8b5172 (do not edit this line) */
